# Generated by Django 2.2.5 on 2020-01-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remindme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_rmndr',
            name='reminder',
            field=models.TextField(),
        ),
    ]
